"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['lyricfetcher/lyricfetcher.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['rumps', 'jinja2', 'os', 'webbrowser', 'bs4', 're', 'requests', 'pkg_resources']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
